(use-modules (scripts lib html)
             (ice-9 rdelim))

(define kjv-book-names
  '(("Ge"    . "Genesis")
    ("Exo"   . "Exodus")
    ("Lev"   . "Leviticus")
    ("Num"   . "Numbers")
    ("Deu"   . "Deuteronomy")
    ("Josh"  . "Joshua")
    ("Jdgs"  . "Judges")
    ("Ruth"  . "Ruth")
    ("1Sm"   . "1 Samuel")
    ("2Sm"   . "2 Samuel")
    ("1Ki"   . "1 Kings")
    ("2Ki"   . "2 Kings")
    ("1Chr"  . "1 Chronicles")
    ("2Chr"  . "2 Chronicles")
    ("Ezra"  . "Ezra")
    ("Neh"   . "Nehemiah")
    ("Est"   . "Esther")
    ("Job"   . "Job")
    ("Psa"   . "Psalms")
    ("Prv"   . "Proverbs")
    ("Eccl"  . "Ecclesiastes")
    ("SSol"  . "Song of Solomon")
    ("Isa"   . "Isaiah")
    ("Jer"   . "Jeremiah")
    ("Lam"   . "Lamentations")
    ("Eze"   . "Ezekiel")
    ("Dan"   . "Daniel")
    ("Hos"   . "Hosea")
    ("Joel"  . "Joel")
    ("Amos"  . "Amos")
    ("Obad"  . "Obadiah")
    ("Jonah" . "Jonah")
    ("Mic"   . "Micah")
    ("Nahum" . "Nahum")
    ("Hab"   . "Habakkuk")
    ("Zep"   . "Zephaniah")
    ("Hag"   . "Haggai")
    ("Zec"   . "Zechariah")
    ("Mal"   . "Malachi")
    ("Mat"   . "Matthew")
    ("Mark"  . "Mark")
    ("Luke"  . "Luke")
    ("John"  . "John")
    ("Acts"  . "Acts")
    ("Rom"   . "Romans")
    ("1Cor"  . "1 Corinthians")
    ("2Cor"  . "2 Corinthians")
    ("Gal"   . "Galatians")
    ("Eph"   . "Ephesians")
    ("Phi"   . "Philippians")
    ("Col"   . "Colossians")
    ("1Th"   . "1 Thessalonians")
    ("2Th"   . "2 Thessalonians")
    ("1Tim"  . "1 Timothy")
    ("2Tim"  . "2 Timothy")
    ("Titus" . "Titus")
    ("Phmn"  . "Philemon")
    ("Heb"   . "Hebrews")
    ("Jas"   . "James")
    ("1Pet"  . "1 Peter")
    ("2Pet"  . "2 Peter")
    ("1Jn"   . "1 John")
    ("2Jn"   . "2 John")
    ("3Jn"   . "3 John")
    ("Jude"  . "Jude")
    ("Rev"   . "Revelation")))

(define (text->id text)
  (string-downcase
   (string-map (lambda (c) (if (char=? c #\space) #\- c)) text)))

(define (kjv-abbr line)
  ;; Handles both "Ge1:1" (letters first) and "1Chr1:1" (digit+letters first).
  ;; Returns the abbreviation string, or #f if the line isn't a verse.
  (let ((len (string-length line)))
    (if (and (> len 0) (char-numeric? (string-ref line 0)))
        ;; Numbered book: digit then letters then digit (chapter)
        (let scan-letters ((i 1))
          (cond
           ((>= i len) #f)
           ((char-alphabetic? (string-ref line i))
            (let scan-end ((j (+ i 1)))
              (cond
               ((>= j len) #f)
               ((char-numeric? (string-ref line j)) (substring line 0 j))
               (else (scan-end (+ j 1))))))
           (else #f)))
        ;; Regular book: letters then digit (chapter)
        (let scan-end ((i 0))
          (cond
           ((>= i len) #f)
           ((char-numeric? (string-ref line i))
            (if (> i 0) (substring line 0 i) #f))
           (else (scan-end (+ i 1))))))))

(define (kjv-full-name abbr)
  (let ((pair (assoc abbr kjv-book-names)))
    (and pair (cdr pair))))

(define (book-heading book)
  (let ((id (text->id book)))
    `(h2 (a (@ (id ,id) (href ,(string-append "#" id))) ,book))))

(define (read-kjv-nodes filename)
  (with-input-from-file filename
    (lambda ()
      (let* ((header (read-line))
             (header-node (string-append header "\n")))
        (let loop ((line (read-line))
                   (current-abbr #f)
                   (nodes (list header-node)))
          (if (eof-object? line)
              (reverse nodes)
              (let* ((abbr (kjv-abbr line))
                     (full (and abbr (kjv-full-name abbr))))
                (if (and full (not (equal? abbr current-abbr)))
                    (loop (read-line) abbr
                          (cons (string-append line "\n")
                                (cons (book-heading full) nodes)))
                    (loop (read-line) current-abbr
                          (cons (string-append line "\n") nodes))))))))))

(render-template "Ursinia - KJV" "bible"
  `((header
      (div (@ (id "header"))
           (span (@ (id "header-bible-versions"))
                 (a (@ (id "header-bible-versions-link")
                        (href "/bible/versions/"))
                    ,(string #\x21a4) " " (code "versions")))))
    (h1 (a (@ (id "title") (href "#full-text")) "KJV"))
    (div (@ (id "resources"))
         (a (@ (href "#resources")) "Self Hosted (downloads a file)")
         (ul
           (li (a (@ (href "/assets/bible/data/versions/kjv.txt")) "KJV - Source"))))
    (div (@ (id "full-text"))
         (pre ,@(read-kjv-nodes "assets/bible/data/versions/kjv.txt")))))
