name: Deploy Ursinia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  HOSTNAME: ursinia.net

jobs:
  deploy:
    name: Deploy ${{ matrix.subdomain }}.${{ env.HOSTNAME }}
    uses: ./.github/workflows/call-deploy-site.yaml
    strategy:
      fail-fast: true
      matrix:
        subdomains:
          - bible
          - charter
          - food
          - home
          - mama
          - papa
          - sitemap
          - sunshine
          - todo
    with:
      hostname: ${{ env.HOSTNAME }}
      subdomain: ${{ matrix.subdomain }}

