name: CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Trigger Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Dispatch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.FG_PAT }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'jamesaorson',
              repo: 'ursinia.net',
              workflow_id: 'deploy.yml',
              ref: 'main',
              inputs: {
                ref: context.ref
              }
            });
