name: Deploy Ursinia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy ${{ matrix.subdomain }}
    uses: ./.github/workflows/call-deploy-site.yaml
    strategy:
      fail-fast: true
      matrix:
        subdomains:
          - bible
          - charter
          - food
          - home
          - mama
          - papa
          - sitemap
          - sunshine
          - todo
    with:
      hostname: ursinia.net
      subdomain: ${{ matrix.subdomain }}

