name: Mirror
on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: jamesaorson/composite-git-mirror@main
        with:
          target-git-url: git@git.sr.ht:~${{ github.repository }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
